/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package serial_read;

import arduino.Arduino;
import embedded.mas.bridges.javard.Arduino4EmbeddedMas;

import com.fazecast.jSerialComm.*;

public class SerialRead {
   
    public static void main(String[] args) {
        
        Arduino a = new Arduino4EmbeddedMas("/dev/ttyUSB0", 9600);      
        a.openConnection();
        
        String s = a.serialRead(); //read from serial until getting a linebreak (\n)
        System.out.println(s);
        
        
    }
}
