/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package serial_read;

import embedded.mas.bridges.javard.Arduino4EmbeddedMas;
import embedded.mas.bridges.jacamo.IPhysicalInterface;

public class SerialRead {
   
    public static void main(String[] args) {
        
        IPhysicalInterface a = new Arduino4EmbeddedMas("/dev/ttyUSB0", 9600); //Arduino4EmbeddedMas can be replaced by any IPhysicalInterface to be tested

        String s = a.read(); //read from serial until getting a linebreak (\n)
        System.out.println(s);                
    }
}
