/*
   Project architecture_1

   Gradle build file for JaCaMo Applications
   outubro 13, 2020 - 09:36:07
*/

defaultTasks 'run'

apply plugin: 'java'
apply plugin: 'eclipse'

version '1.0'
group   'org.jacamo'

// sourceCompatibility = 1.8
// targetCompatibility = 1.8

repositories {
    maven { url "https://raw.githubusercontent.com/jacamo-lang/mvn-repo/master" }
    maven { url "https://repo.gradle.org/gradle/libs-releases" }
    maven { url "https://raw.github.com/embedded-mas/embedded-mas-mvn-repo/master" }



    flatDir { dirs 'lib' }

    mavenCentral()

}

dependencies {
    implementation 'org.jacamo:jacamo:1.2.3'
    //implementation "embedded-mas:embedded-mas:0.056-SNAPSHOT" 
    implementation files('/mnt/1C4C766F4C764414/maiquel/git/embedded-mas-multi-device-actuations/embedded-mas/build/libs/embedded-mas-0.060-SNAPSHOT.jar')
    implementation "javard:javard:0.032-SNAPSHOT"
    
    //daqui para baixo, testar se dá pra eliminar quando usar o repositório do embedded-mas em vez de arquivo jar local
    implementation group: 'org.yaml', name: 'snakeyaml', version: '1.30'
    implementation group: 'com.fasterxml.jackson.dataformat', name: 'jackson-dataformat-yaml', version: '2.13.3'
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.13.3'
}

sourceSets {
    main {
        java {
            srcDir 'src/env'
            srcDir 'src/agt'
            srcDir 'src/org'
            srcDir 'src/java'
        }
        resources {
            srcDir 'src/resources'
        }
    }
}

// task run (type: JavaExec, dependsOn: 'classes') {
//     group       ' JaCaMo'
//     description 'runs the JaCaMo application'
//     doFirst {
//         mkdir 'log'
//     }
//     main 'jacamo.infra.JaCaMoLauncher'
//     args 'perception_action.jcm'
//     classpath sourceSets.main.runtimeClasspath
// }


task run (type: JavaExec, dependsOn: ['compileGeneratedInternalActions','classes']) {
    group       ' JaCaMo'
    description 'runs the JaCaMo application'
    mainClass = 'jacamo.infra.JaCaMoLauncher'
    args 'perception_action.jcm'
    // jvmArgs '-Xss15m'
    classpath sourceSets.main.runtimeClasspath
}


// Generate internal actions corresponding to actions specified in the yaml files
task generateInternalActions(type: JavaExec) {
    group = 'Application'
    description = 'Generate internal actions corresponding to actions specidied in the yaml files'
    classpath = sourceSets.main.runtimeClasspath
    main = 'embedded.mas.bridges.jacamo.InternalActionGenerator'
    outputs.dir 'src/java/jason/stdlib'
}


// Compile internal actions
task compileGeneratedInternalActions(type: JavaCompile, dependsOn: ['generateInternalActions']) {
    // Specifies the source files to compile after the generation task has run
    source = fileTree("src/java/jason/stdlib/") {
        include '**/*.java' // Include Java files from the generated sources
    }
    classpath = sourceSets.main.compileClasspath    
    destinationDir = destinationDir = file("$buildDir/classes/java/main") // Target directory for compilation
}




clean {
    delete 'bin'
    delete 'build'
    delete 'log'
}
